---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This is the website for the research project "Multiclass AUC".
See the [About](about.html) page for a summary description of this project.

If you have cloned the project to a local computer this website is
rendered in the `docs` subdirectory of the project directory.

If you are using `workflowr` to publish the research website it will
also be rendered online to GitHub Pages.

**This page acts as a table of contents for the website.**\
There are links below to the web pages generated from the analysis notebooks.

------------------------------------------------------------------------

## [01_read_data](01_read_data.html) {.unnumbered}

Read the example datasets, calculate some check counts, reformat the data for analysis, and save to an R data file.

## [02_check_data](02_check_data.html) {.unnumbered}

Check the ranges of the variables in the example data.

## [03_plot_independent_distributions](03_plot_independent_distributions.html) {.unnumbered}

Investigate the distribution of each class score in response to cases of each class.

## [04_score_dependencies](04_score_dependencies.html) {.unnumbered}

Investigate the dependencies between all the class scores calculated on the same case.

## [05_score_calibration_1](05_score_calibration_1.html) {.unnumbered}

Investigate the the scaling and calibration of the class scores (first attempt).


## [06_class_pair_synthetic_score](06_class_pair_synthetic_score.html) {.unnumbered}

Introduce the concept of a synthetic score to combine the two class scores into a single score.




